### ISSUE TITLE
inline_tests work on v0.15.1 but not on v0.16.0

### ISSUE THREAD

**Issue by mooreryan** [janestreet/bonsai#37]
I think I must be doing something obviously wrong here...but I can't get the inline tests to work with v0.16.0.

```ocaml
open! Core

let component = Bonsai.const Bonsai_web.Vdom.Node.(p [text "hello world"])

module Test = struct
  module Handle = Bonsai_web_test.Handle
  module Result_spec = Bonsai_web_test.Result_spec

  let%expect_test "it shows hello world" =
    let handle = Handle.create (Result_spec.vdom Fn.id) component in
    Handle.show handle ; [%expect {|  |}]
end
```

dune file

```
(library
 (name hi)
 (inline_tests
  (modes js))
 (libraries core bonsai.web bonsai.web_test)
 (preprocess
  (pps ppx_jane)))
```

Error when running tests

```
File "src/lib/test/dune", line 3, characters 1-28:
3 |  (inline_tests
4 |   (modes js))
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'deasync'
Require stack:
- /home/ryan/projects/pubmed_reader_stuff/pubmed_reader_7/pubmed_reader/_build/default/src/lib/test/.lib_test.inline-tests/inline_test_runner_lib_test.bc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /home/ryan/projects/pubmed_reader_stuff/pubmed_reader_7/pubmed_reader/_build/default/src/lib/test/.lib_test.inline-tests/inline_test_runner_lib_test.bc.js:4158:18
    at Object.<anonymous> (/home/ryan/projects/pubmed_reader_stuff/pubmed_reader_7/pubmed_reader/_build/default/src/lib/test/.lib_test.inline-tests/inline_test_runner_lib_test.bc.js:11581:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ryan/projects/pubmed_reader_stuff/pubmed_reader_7/pubmed_reader/_build/default/src/lib/test/.lib_test.inline-tests/inline_test_runner_lib_test.bc.js'
  ]
}

Node.js v18.11.0
```

Switching back to the v0.15.1 release of bonsai, the above works fine.

**Comment by mooreryan** [comment]
I also tried to set up the dune file as in the blog post on testing (https://github.com/janestreet/bonsai/blob/master/docs/blogs/testing.mdx):

```
(library (
  (name my_ui_test)
  (js_of_ocaml ())                   ; Test library must be marked with js_of_ocaml
  (libraries (core my_ui))
  (inline_tests (                    ; Native tests must be disabled
    (native     dont_build_dont_run)
    (javascript build_and_run)))))
```

But that gave other dune errors, so I'm assuming that isn't part of the solution.

**Comment by mooreryan** [comment]
Here is a "minimum" example that triggers the error when running `dune runtest`:

dune file

```
(library
 (name hi)
 (inline_tests
  (modes js))
 (libraries bonsai.web_test)
 (preprocess
  (pps ppx_inline_test)))
```

OCaml file

```ocaml
let%test _ = 1 = 2
```

**Comment by mooreryan** [comment]
So, I found a fix.  I noticed that the bonsai.web_test pulls in `async_js.async_test` ([here](https://github.com/janestreet/bonsai/blob/3b0e9e24d5a8ce7a655e62cada1e1f059605c823/web_test/dune#L2)).  Went to check on the runtime [there](https://github.com/janestreet/async_js/blob/d0c428306cf262797a3cc1f12380ee72db8a3d42/async_js_test/src/runtime.js#L2) and saw it required some JS package deasync ([this](https://github.com/abbr/deasync)).  

So in the root of my project I ran `npm install deasync`, then reran the tests and it worked.

**Comment by mooreryan** [comment]
So, I guess my question now is, is the `npm install deasync` the "correct" thing to do?  (Well, it works so I will use it for now.)

**Comment by TyOverby** [comment]
Ah, yes that is the right package, but I'm a bit surprised that deasync is required if you aren't using our bonsai-test + async integration.  I'll look into this

**Comment by Knaoinr** [comment]
This looks fixed ([bonsai_web_test](https://github.com/janestreet/bonsai_web_test/blob/master/dune) no longer depends on `async_js.async_test` - only [bonsai_web_test.async](https://github.com/janestreet/bonsai_web_test/blob/master/async/dune) does). Let us know if you're still having issues though!
